language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- npm run test-headless
- ng build --prod --base-href https://mortezaaghili.github.io/movie-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/movie-app
  on:
    branch: master
